theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
bitrate = true
interval = 5
speed_down = false
speed_up = false
graph_down = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
interval = 1
format = "{average}°"
collapsed = false
chip = "*-isa-*"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 1
device = "BAT1"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"
