#!/bin/bash

choice="Docked 2160\nDocked 1080\nMobile"

chosen=$(echo -e "$choice" | dmenu -i)

case "$chosen" in
    "Docked 1080") xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-1 --off \
        --output DP-2 --off
        ;;
    "Docked 2160") xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 3840x1080 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --mode 3840x2160 --pos 0x0 --rotate normal \
        --output DP-1 --off \
        --output DP-2 --off
        ;;
    Mobile) xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --off \
        --output DP-2 --off
        ;;
esac

